server:
  port: 8401

spring:
  application:
    name: cloudalibaba-sentinel-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 #Nacos服务注册中心地址
    sentinel:
      transport:
        # dashboard: 172.17.0.7:8719   # 配置Sentinel dashboard地址；8080 将会监控 8401
        dashboard: 172.16.100.4:8858   # Linux docker 安装的 Sentinel dashboard地址
        port: 8719 # 默认端口，假如被占用，会自动从8719开始依次+1扫描，直至找到未被占用的端口
      datasource:  # ⚪️ 这一块
        ds1:
          nacos:
            server-addr: localhost:8848
            # dataId: cloudalibaba-sentinel-service  # 指定应用名
            dataId: ${spring.application.name}       # 使用变量添加应用名
            groupId: DEFAULT_GROUP
            data-type: json
            rule-type: flow

# 图形化展现
management:
  endpoints:
    web:
      exposure:
        include: '*'

feign:
  sentinel:
    enabled: true # 激活Sentinel对Feign的支持



